services:
  # Backend API
  backend:
    build: .
    container_name: landing-page-template-api
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGODB=mongodb://host.docker.internal:27017/landing-template?retryWrites=true&w=majority
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - BACKUP_STORAGE_PATH=/app/backups
    env_file:
      - .env
    volumes:
      # Persist backups, logs and uploads
      - ./backups:/app/backups
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
